name: sub

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

jobs:
  subjob:
    runs-on: ubuntu-latest
    steps:
      - name: sub Hello
        run: echo 'Hello ${{ inputs.name}}. My secret is ${{ secrets.MY_SECRET }}.'
